spring:
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.H2Dialect
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:test_mem;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
  jackson:
    serialization:
      write_dates_as_timestamps: false
    default-property-inclusion: NON_NULL
  flyway:
    locations:
      - classpath:db/migration
    enabled: true
    baseline-on-migrate: true
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  error:
    include-message: always

logging:
  pattern:
    console: "%d %-5level [%thread] %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    root: ERROR
    org.springframework.web: ERROR
    br.com.digix.avaliadorfamilia: DEBUG
    org.hibernate: ERROR