INSERT INTO FAMILIA(ID, RENDA_TOTAL) VALUES (2, 900);
INSERT INTO FAMILIA(ID, RENDA_TOTAL) VALUES (3, 901);
INSERT INTO FAMILIA(ID, RENDA_TOTAL) VALUES (4, 1500);
INSERT INTO FAMILIA(ID, RENDA_TOTAL) VALUES (5, 5000);
INSERT INTO FAMILIA(ID, RENDA_TOTAL) VALUES (6, 700);
INSERT INTO FAMILIA(ID, RENDA_TOTAL) VALUES (7, 700);
INSERT INTO FAMILIA(ID, RENDA_TOTAL) VALUES (8, 10000);
INSERT INTO FAMILIA(ID, RENDA_TOTAL) VALUES (9, 800);


INSERT INTO DEPENDENTE(ID, NOME, IDADE, ID_FAMILIA) VALUES (4, 'TESTE 1', 18, 2);
INSERT INTO DEPENDENTE(ID, NOME, IDADE, ID_FAMILIA) VALUES (5, 'TESTE 2', 15, 2);
INSERT INTO DEPENDENTE(ID, NOME, IDADE, ID_FAMILIA) VALUES (6, 'TESTE 3', 12, 2);
INSERT INTO DEPENDENTE(ID, NOME, IDADE, ID_FAMILIA) VALUES (7, 'TESTE 4', 10, 3);
INSERT INTO DEPENDENTE(ID, NOME, IDADE, ID_FAMILIA) VALUES (8, 'TESTE 5', 15, 4);
INSERT INTO DEPENDENTE(ID, NOME, IDADE, ID_FAMILIA) VALUES (9, 'TESTE 6', 12, 5);
INSERT INTO DEPENDENTE(ID, NOME, IDADE, ID_FAMILIA) VALUES (10, 'TESTE 7', 15, 5);
INSERT INTO DEPENDENTE(ID, NOME, IDADE, ID_FAMILIA) VALUES (11, 'TESTE 8', 10, 6);
INSERT INTO DEPENDENTE(ID, NOME, IDADE, ID_FAMILIA) VALUES (12, 'TESTE 9', 8, 6);
INSERT INTO DEPENDENTE(ID, NOME, IDADE, ID_FAMILIA) VALUES (13, 'TESTE 10', 15, 6);
INSERT INTO DEPENDENTE(ID, NOME, IDADE, ID_FAMILIA) VALUES (14, 'TESTE 11', 18, 7);
INSERT INTO DEPENDENTE(ID, NOME, IDADE, ID_FAMILIA) VALUES (15, 'TESTE 12', 10, 8);
INSERT INTO DEPENDENTE(ID, NOME, IDADE, ID_FAMILIA) VALUES (16, 'TESTE 13', 10, 9);
